# Generated by Django 3.2 on 2021-04-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Data_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Data_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Place_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Data_id', models.CharField(max_length=30)),
            ],
        ),
    ]
