# Generated by Django 3.2 on 2021-04-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField(max_length=30)),
                ('City_name', models.CharField(max_length=30)),
                ('Place_name', models.CharField(max_length=30)),
                ('Country_id', models.CharField(max_length=30)),
                ('City_id', models.CharField(max_length=30)),
                ('Place_id', models.CharField(max_length=30)),
            ],
        ),
    ]
